version: '3.9'

services:
  app: #the application we want to run
    build:
      context: .
      args:
        - DEV=true
    ports: #porting the port 8000 on our local machine inside the docker container
      - "8000:8000"
    volumes: #mapping the directories into docker container
      - ./app:/app
    command: python manage.py runserver 0.0.0.0:8000
