version: '3.9'

services:
  app: #the application we want to run
    build:
      context: .
      args:
        - DEV=true
    ports: #porting the port 8000 on our local machine inside the docker container
      - "8000:8000"
    volumes: #mapping the directories into docker container
      - ./app:/app
    command: > #this command is for waiting for db to be up then to migrate the database and then run the server.
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    ports: #new code
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
    #To set the initial database configuration for new db service.
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme


volumes:
  dev-db-data:
  dev-static-data: