#This file is the configuration files for github actions
---
name: Checks

#this runs the jubs specified below whenever the commit is done
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
    #name is the name of the tast that we will see in the github user interface
      - name: Login to Docker Hub 
        uses: docker/login-action@v1
        with:
        #step1-below are th docker login credentials
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #step2 - checkout 
      - name: Checkout
        uses: actions/checkout@v2
      #step3- testing and linting
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"